server: 
  port: 7001
eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    service-url:
        defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:${server.port}/eureka/
  server:  
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上，默认30s
    #responseCacheUpdateInvervalMs: 3000 
    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。默认180s
    #responseCacheAutoExpirationInSeconds: 180
    #该配置可以移除这种自我保护机制，防止失效的服务也被一直访问 (Spring Cloud默认该配置是 true)
    enableSelfPreservation: false
    #该配置可以修改检查失效服务的时间，每隔3s检查失效服务，并移除列表 (Spring Cloud默认该配置是 60s，单位毫秒)
    evictionIntervalTimerInMs: 3000
# 安全认证的配置    
security: 
  basic:    
    enabled: true    
  user:    
    name: admin
    password: admin
  