server: 
  port: 7008
  tomcat: 
  uri-encoding :  UTF-8
spring: 
  application: 
    name: spring-boot-service-b
eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/
