server: 
  port: 7006
  uri-encoding :  UTF-8
spring: 
  application: 
    name: spring-boot-service-c
  thymeleaf: 
    encoding: UTF-8
    cache: false
eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/
